# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - EduVisor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v3.2.0
        with:
          registry: https://eduvisorcr.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_8d6002f267154c6ea62d352c84ca52e9 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_ed3e5d521c1b4f31a063c5246984d2ac }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          tags: eduvisorcr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8d6002f267154c6ea62d352c84ca52e9 }}/eduvisor:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "EduVisor"
          slot-name: "Production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_461047d0c30b4cf68afa31c2487d46c0 }}
          images: "eduvisorcr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8d6002f267154c6ea62d352c84ca52e9 }}/eduvisor:${{ github.sha }}"
