name: Build and deploy Node.js app to Azure Web App - EduvisorTP2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up Node.js version
        uses: actions/setup-node@v4.0.3
        with:
          node-version: "20.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Compress files
        run: |
          Compress-Archive -Path * -CompressionLevel Optimal -DestinationPath node-app.zip -Force
        shell: pwsh

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4.3.6
        with:
          name: node-app
          path: node-app.zip # Subir el archivo comprimido

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4.1.8
        with:
          name: node-app

      - name: Extract artifact
        run: unzip node-app.zip

      - name: Login to Azure
        uses: azure/login@v2.1.1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5DF338C4991646C382F518F7F2634B3D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F7CA3F77DD7A49759AAFD26DD67917EE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_549A2C7DC5BC4863865E2A8B8B4D83C4 }}

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "EduvisorTP2"
          slot-name: "production"
          package: .
